/* eslint-env mocha */

'use strict'

const flobot = require('flobot')
const path = require('path')
const expect = require('chai').expect

describe('data import', function () {
  this.timeout(5000)

  const STATE_MACHINE_NAME = 'dclg_refreshFromCsvFile_1_0'

  let statebox
  let client

  it('should startup flobot', function (done) {
    flobot.boot(
      {
        pluginPaths: [
          require.resolve('flobot-pg-plugin')
        ],
        blueprintPaths: [
          path.resolve(__dirname, './../')
        ],
        config: {}
      },
      function (err, flobotServices) {
        expect(err).to.eql(null)
        statebox = flobotServices.statebox
        client = flobotServices.storage.client
        done()
      }
    )
  })

  it('should create and populate the dclg.imd database table', function (done) {
    statebox.startExecution(
      {
        sourceDir: path.resolve(__dirname, './fixtures/input')
      },  // input
      STATE_MACHINE_NAME, // state machine name
      {
        sendResponse: 'COMPLETE'
      }, // options
      function (err, executionDescription) {
        expect(err).to.eql(null)
        expect(executionDescription.status).to.eql('SUCCEEDED')
        expect(executionDescription.currentStateName).to.eql('ImportingCsvFiles')
        done()
      }
    )
  })

  it('Should be the correct data in the database', function (done) {
    client.query(
      'select lsoa_code_2011, lsoa_name_2011, local_authority_district_code_2013, local_authority_district_name_2013 ' +
      'index_of_multiple_deprivation_score, index_of_multiple_deprivation_rank, index_of_multiple_deprivation_decile, ' +
      'income_score, income_rank, income_decile, employment_score, employment_rank, employment_decile, ' +
      'education_skills_and_training_score, education_skills_and_training_rank, education_skills_and_training_decile, ' +
      'health_deprivation_and_disability_score, health_deprivation_and_disability_rank, health_deprivation_and_disability_decile, ' +
      'crime_score, crime_rank, crime_decile, barriers_to_housing_and_services_score, barriers_to_housing_and_services_rank, ' +
      'barriers_to_housing_and_services_decile, living_environment_score, living_environment_rank, living_environment_decile, ' +
      'income_deprivation_affecting_children_index_score, income_deprivation_affecting_children_index_rank, ' +
      'income_deprivation_affecting_children_index_decile, income_deprivation_affecting_older_people_score, ' +
      'income_deprivation_affecting_older_people_rank, income_deprivation_affecting_older_people_decile, ' +
      'children_and_young_people_subdomain_score, children_and_young_people_subdomain_rank, ' +
      'children_and_young_people_subdomain_decile, adult_skills_subdomain_score, adult_skills_subdomain_rank, ' +
      'adult_skills_subdomain_decile, geographical_barriers_subdomain_score, geographical_barriers_subdomain_rank, ' +
      'geographical_barriers_subdomain_decile, wider_barriers_subdomain_score, wider_barriers_subdomain_rank, ' +
      'wider_barriers_subdomain_decile, indoors_subdomain_score, indoors_subdomain_rank, indoors_subdomain_decile, ' +
      'outdoors_subdomain_score, outdoors_subdomain_rank, outdoors_subdomain_decile, total_population_mid_2012, ' +
      'dependent_children_aged_015_mid_2012, population_aged_1659_mid_2012, older_population_aged_60_and_over_mid_2012, ' +
      'working_age_population_185964 from dclg.imd order by lsoa_code_2011;',
      function (err, result) {
        expect(err).to.equal(null)
        if (err) {
          done(err)
        } else {
          expect(result.rows).to.eql(
            [
              {
                lsoa_code_2011: 'E01031338',
                lsoa_name_2011: 'Adur 002A',
                local_authority_district_code_2013: 'E07000223',
                index_of_multiple_deprivation_score: 'Adur',
                index_of_multiple_deprivation_rank: '27934',
                index_of_multiple_deprivation_decile: '9',
                income_score: '0.063',
                income_rank: '25105',
                income_decile: '8.000',
                employment_score: '0.062',
                employment_rank: '24672',
                employment_decile: '8',
                education_skills_and_training_score: '8.597',
                education_skills_and_training_rank: '23320',
                education_skills_and_training_decile: '8',
                health_deprivation_and_disability_score: '-0.241',
                health_deprivation_and_disability_rank: '19734',
                health_deprivation_and_disability_decile: '7',
                crime_score: '-0.565',
                crime_rank: '24708',
                crime_decile: '8',
                barriers_to_housing_and_services_score: '8.463',
                barriers_to_housing_and_services_rank: '30180',
                barriers_to_housing_and_services_decile: '10',
                living_environment_score: '11.207',
                living_environment_rank: '22234',
                living_environment_decile: '7',
                income_deprivation_affecting_children_index_score: '0.065',
                income_deprivation_affecting_children_index_rank: '26129',
                income_deprivation_affecting_children_index_decile: '8',
                income_deprivation_affecting_older_people_score: '0.082',
                income_deprivation_affecting_older_people_rank: '25634',
                income_deprivation_affecting_older_people_decile: '8',
                children_and_young_people_subdomain_score: '-0.294',
                children_and_young_people_subdomain_rank: '20895',
                children_and_young_people_subdomain_decile: '7',
                adult_skills_subdomain_score: '0.229',
                adult_skills_subdomain_rank: '24157',
                adult_skills_subdomain_decile: '8',
                geographical_barriers_subdomain_score: '-0.426',
                geographical_barriers_subdomain_rank: '23067',
                geographical_barriers_subdomain_decile: '8',
                wider_barriers_subdomain_score: '-1.221',
                wider_barriers_subdomain_rank: '22145',
                wider_barriers_subdomain_decile: '7',
                indoors_subdomain_score: '-0.726',
                indoors_subdomain_rank: '26167',
                indoors_subdomain_decile: '8',
                outdoors_subdomain_score: '0.289',
                outdoors_subdomain_rank: '11644',
                outdoors_subdomain_decile: '4',
                total_population_mid_2012: '1167',
                dependent_children_aged_015_mid_2012: '192',
                population_aged_1659_mid_2012: '612',
                older_population_aged_60_and_over_mid_2012: '363',
                working_age_population_185964: '622.50'
              },
              {
                lsoa_code_2011: 'E01031339',
                lsoa_name_2011: 'Adur 002B',
                local_authority_district_code_2013: 'E07000223',
                index_of_multiple_deprivation_score: 'Adur',
                index_of_multiple_deprivation_rank: '28249',
                index_of_multiple_deprivation_decile: '9',
                income_score: '0.072',
                income_rank: '23260',
                income_decile: '8.000',
                employment_score: '0.054',
                employment_rank: '26753',
                employment_decile: '9',
                education_skills_and_training_score: '3.882',
                education_skills_and_training_rank: '28719',
                education_skills_and_training_decile: '9',
                health_deprivation_and_disability_score: '-0.472',
                health_deprivation_and_disability_rank: '22885',
                health_deprivation_and_disability_decile: '7',
                crime_score: '-1.473',
                crime_rank: '31928',
                crime_decile: '10',
                barriers_to_housing_and_services_score: '19.940',
                barriers_to_housing_and_services_rank: '16896',
                barriers_to_housing_and_services_decile: '6',
                living_environment_score: '13.118',
                living_environment_rank: '20275',
                living_environment_decile: '7',
                income_deprivation_affecting_children_index_score: '0.134',
                income_deprivation_affecting_children_index_rank: '17609',
                income_deprivation_affecting_children_index_decile: '6',
                income_deprivation_affecting_older_people_score: '0.063',
                income_deprivation_affecting_older_people_rank: '28828',
                income_deprivation_affecting_older_people_decile: '9',
                children_and_young_people_subdomain_score: '-0.915',
                children_and_young_people_subdomain_rank: '28586',
                children_and_young_people_subdomain_decile: '9',
                adult_skills_subdomain_score: '0.204',
                adult_skills_subdomain_rank: '26798',
                adult_skills_subdomain_decile: '9',
                geographical_barriers_subdomain_score: '0.512',
                geographical_barriers_subdomain_rank: '7829',
                geographical_barriers_subdomain_decile: '3',
                wider_barriers_subdomain_score: '-1.431',
                wider_barriers_subdomain_rank: '23245',
                wider_barriers_subdomain_decile: '8',
                indoors_subdomain_score: '-0.535',
                indoors_subdomain_rank: '23982',
                indoors_subdomain_decile: '8',
                outdoors_subdomain_score: '0.353',
                outdoors_subdomain_rank: '10741',
                outdoors_subdomain_decile: '4',
                total_population_mid_2012: '1157',
                dependent_children_aged_015_mid_2012: '206',
                population_aged_1659_mid_2012: '657',
                older_population_aged_60_and_over_mid_2012: '294',
                working_age_population_185964: '666.25'
              },
              {
                lsoa_code_2011: 'E01031340',
                lsoa_name_2011: 'Adur 002C',
                local_authority_district_code_2013: 'E07000223',
                index_of_multiple_deprivation_score: 'Adur',
                index_of_multiple_deprivation_rank: '27569',
                index_of_multiple_deprivation_decile: '9',
                income_score: '0.036',
                income_rank: '30776',
                income_decile: '10.000',
                employment_score: '0.041',
                employment_rank: '30033',
                employment_decile: '10',
                education_skills_and_training_score: '13.214',
                education_skills_and_training_rank: '18895',
                education_skills_and_training_decile: '6',
                health_deprivation_and_disability_score: '-0.675',
                health_deprivation_and_disability_rank: '25426',
                health_deprivation_and_disability_decile: '8',
                crime_score: '0.334',
                crime_rank: '11383',
                crime_decile: '4',
                barriers_to_housing_and_services_score: '16.057',
                barriers_to_housing_and_services_rank: '21712',
                barriers_to_housing_and_services_decile: '7',
                living_environment_score: '12.964',
                living_environment_rank: '20427',
                living_environment_decile: '7',
                income_deprivation_affecting_children_index_score: '0.042',
                income_deprivation_affecting_children_index_rank: '29740',
                income_deprivation_affecting_children_index_decile: '10',
                income_deprivation_affecting_older_people_score: '0.055',
                income_deprivation_affecting_older_people_rank: '30083',
                income_deprivation_affecting_older_people_decile: '10',
                children_and_young_people_subdomain_score: '-0.046',
                children_and_young_people_subdomain_rank: '16970',
                children_and_young_people_subdomain_decile: '6',
                adult_skills_subdomain_score: '0.267',
                adult_skills_subdomain_rank: '19739',
                adult_skills_subdomain_decile: '7',
                geographical_barriers_subdomain_score: '0.406',
                geographical_barriers_subdomain_rank: '9220',
                geographical_barriers_subdomain_decile: '3',
                wider_barriers_subdomain_score: '-2.461',
                wider_barriers_subdomain_rank: '27972',
                wider_barriers_subdomain_decile: '9',
                indoors_subdomain_score: '-0.874',
                indoors_subdomain_rank: '27685',
                indoors_subdomain_decile: '9',
                outdoors_subdomain_score: '0.552',
                outdoors_subdomain_rank: '8163',
                outdoors_subdomain_decile: '3',
                total_population_mid_2012: '1477',
                dependent_children_aged_015_mid_2012: '215',
                population_aged_1659_mid_2012: '729',
                older_population_aged_60_and_over_mid_2012: '533',
                working_age_population_185964: '747.25'
              },
              {
                lsoa_code_2011: 'E01031349',
                lsoa_name_2011: 'Adur 001A',
                local_authority_district_code_2013: 'E07000223',
                index_of_multiple_deprivation_score: 'Adur',
                index_of_multiple_deprivation_rank: '21352',
                index_of_multiple_deprivation_decile: '7',
                income_score: '0.096',
                income_rank: '18992',
                income_decile: '6.000',
                employment_score: '0.083',
                employment_rank: '19305',
                employment_decile: '6',
                education_skills_and_training_score: '20.055',
                education_skills_and_training_rank: '13727',
                education_skills_and_training_decile: '5',
                health_deprivation_and_disability_score: '-0.718',
                health_deprivation_and_disability_rank: '25876',
                health_deprivation_and_disability_decile: '8',
                crime_score: '0.242',
                crime_rank: '12817',
                crime_decile: '4',
                barriers_to_housing_and_services_score: '10.586',
                barriers_to_housing_and_services_rank: '28166',
                barriers_to_housing_and_services_decile: '9',
                living_environment_score: '15.180',
                living_environment_rank: '18367',
                living_environment_decile: '6',
                income_deprivation_affecting_children_index_score: '0.143',
                income_deprivation_affecting_children_index_rank: '16807',
                income_deprivation_affecting_children_index_decile: '6',
                income_deprivation_affecting_older_people_score: '0.103',
                income_deprivation_affecting_older_people_rank: '22207',
                income_deprivation_affecting_older_people_decile: '7',
                children_and_young_people_subdomain_score: '0.098',
                children_and_young_people_subdomain_rank: '14682',
                children_and_young_people_subdomain_decile: '5',
                adult_skills_subdomain_score: '0.333',
                adult_skills_subdomain_rank: '12380',
                adult_skills_subdomain_decile: '4',
                geographical_barriers_subdomain_score: '-0.346',
                geographical_barriers_subdomain_rank: '21787',
                geographical_barriers_subdomain_decile: '7',
                wider_barriers_subdomain_score: '-0.721',
                wider_barriers_subdomain_rank: '19421',
                wider_barriers_subdomain_decile: '6',
                indoors_subdomain_score: '-0.268',
                indoors_subdomain_rank: '20379',
                indoors_subdomain_decile: '7',
                outdoors_subdomain_score: '0.312',
                outdoors_subdomain_rank: '11318',
                outdoors_subdomain_decile: '4',
                total_population_mid_2012: '1318',
                dependent_children_aged_015_mid_2012: '206',
                population_aged_1659_mid_2012: '694',
                older_population_aged_60_and_over_mid_2012: '418',
                working_age_population_185964: '702.75'
              },
              {
                lsoa_code_2011: 'E01031350',
                lsoa_name_2011: 'Adur 001B',
                local_authority_district_code_2013: 'E07000223',
                index_of_multiple_deprivation_score: 'Adur',
                index_of_multiple_deprivation_rank: '8864',
                index_of_multiple_deprivation_decile: '3',
                income_score: '0.187',
                income_rank: '9233',
                income_decile: '3.000',
                employment_score: '0.162',
                employment_rank: '7879',
                employment_decile: '3',
                education_skills_and_training_score: '34.653',
                education_skills_and_training_rank: '6969',
                education_skills_and_training_decile: '3',
                health_deprivation_and_disability_score: '0.722',
                health_deprivation_and_disability_rank: '6883',
                health_deprivation_and_disability_decile: '3',
                crime_score: '0.244',
                crime_rank: '12781',
                crime_decile: '4',
                barriers_to_housing_and_services_score: '24.689',
                barriers_to_housing_and_services_rank: '11399',
                barriers_to_housing_and_services_decile: '4',
                living_environment_score: '17.837',
                living_environment_rank: '16242',
                living_environment_decile: '5',
                income_deprivation_affecting_children_index_score: '0.211',
                income_deprivation_affecting_children_index_rank: '11629',
                income_deprivation_affecting_children_index_decile: '4',
                income_deprivation_affecting_older_people_score: '0.269',
                income_deprivation_affecting_older_people_rank: '7376',
                income_deprivation_affecting_older_people_decile: '3',
                children_and_young_people_subdomain_score: '0.470',
                children_and_young_people_subdomain_rank: '9187',
                children_and_young_people_subdomain_decile: '3',
                adult_skills_subdomain_score: '0.426',
                adult_skills_subdomain_rank: '5227',
                adult_skills_subdomain_decile: '2',
                geographical_barriers_subdomain_score: '0.234',
                geographical_barriers_subdomain_rank: '11825',
                geographical_barriers_subdomain_decile: '4',
                wider_barriers_subdomain_score: '1.104',
                wider_barriers_subdomain_rank: '10128',
                wider_barriers_subdomain_decile: '4',
                indoors_subdomain_score: '0.016',
                indoors_subdomain_rank: '16285',
                indoors_subdomain_decile: '5',
                outdoors_subdomain_score: '0.234',
                outdoors_subdomain_rank: '12445',
                outdoors_subdomain_decile: '4',
                total_population_mid_2012: '1212',
                dependent_children_aged_015_mid_2012: '232',
                population_aged_1659_mid_2012: '712',
                older_population_aged_60_and_over_mid_2012: '268',
                working_age_population_185964: '720.75'
              },
              {
                lsoa_code_2011: 'E01031351',
                lsoa_name_2011: 'Adur 001C',
                local_authority_district_code_2013: 'E07000223',
                index_of_multiple_deprivation_score: 'Adur',
                index_of_multiple_deprivation_rank: '22143',
                index_of_multiple_deprivation_decile: '7',
                income_score: '0.065',
                income_rank: '24539',
                income_decile: '8.000',
                employment_score: '0.066',
                employment_rank: '23389',
                employment_decile: '8',
                education_skills_and_training_score: '26.334',
                education_skills_and_training_rank: '10213',
                education_skills_and_training_decile: '4',
                health_deprivation_and_disability_score: '-0.616',
                health_deprivation_and_disability_rank: '24693',
                health_deprivation_and_disability_decile: '8',
                crime_score: '0.495',
                crime_rank: '9112',
                crime_decile: '3',
                barriers_to_housing_and_services_score: '13.631',
                barriers_to_housing_and_services_rank: '24743',
                barriers_to_housing_and_services_decile: '8',
                living_environment_score: '11.150',
                living_environment_rank: '22299',
                living_environment_decile: '7',
                income_deprivation_affecting_children_index_score: '0.077',
                income_deprivation_affecting_children_index_rank: '24371',
                income_deprivation_affecting_children_index_decile: '8',
                income_deprivation_affecting_older_people_score: '0.079',
                income_deprivation_affecting_older_people_rank: '26280',
                income_deprivation_affecting_older_people_decile: '9',
                children_and_young_people_subdomain_score: '0.395',
                children_and_young_people_subdomain_rank: '10191',
                children_and_young_people_subdomain_decile: '4',
                adult_skills_subdomain_score: '0.357',
                adult_skills_subdomain_rank: '10129',
                adult_skills_subdomain_decile: '4',
                geographical_barriers_subdomain_score: '0.035',
                geographical_barriers_subdomain_rank: '15211',
                geographical_barriers_subdomain_decile: '5',
                wider_barriers_subdomain_score: '-1.048',
                wider_barriers_subdomain_rank: '21208',
                wider_barriers_subdomain_decile: '7',
                indoors_subdomain_score: '-0.628',
                indoors_subdomain_rank: '25054',
                indoors_subdomain_decile: '8',
                outdoors_subdomain_score: '0.208',
                outdoors_subdomain_rank: '12820',
                outdoors_subdomain_decile: '4',
                total_population_mid_2012: '1577',
                dependent_children_aged_015_mid_2012: '290',
                population_aged_1659_mid_2012: '829',
                older_population_aged_60_and_over_mid_2012: '458',
                working_age_population_185964: '838.25'
              },
              {
                lsoa_code_2011: 'E01031352',
                lsoa_name_2011: 'Adur 001D',
                local_authority_district_code_2013: 'E07000223',
                index_of_multiple_deprivation_score: 'Adur',
                index_of_multiple_deprivation_rank: '17252',
                index_of_multiple_deprivation_decile: '6',
                income_score: '0.117',
                income_rank: '16087',
                income_decile: '5.000',
                employment_score: '0.113',
                employment_rank: '13699',
                employment_decile: '5',
                education_skills_and_training_score: '25.779',
                education_skills_and_training_rank: '10468',
                education_skills_and_training_decile: '4',
                health_deprivation_and_disability_score: '-0.234',
                health_deprivation_and_disability_rank: '19627',
                health_deprivation_and_disability_decile: '6',
                crime_score: '0.026',
                crime_rank: '16127',
                crime_decile: '5',
                barriers_to_housing_and_services_score: '17.803',
                barriers_to_housing_and_services_rank: '19559',
                barriers_to_housing_and_services_decile: '6',
                living_environment_score: '10.677',
                living_environment_rank: '22819',
                living_environment_decile: '7',
                income_deprivation_affecting_children_index_score: '0.210',
                income_deprivation_affecting_children_index_rank: '11693',
                income_deprivation_affecting_children_index_decile: '4',
                income_deprivation_affecting_older_people_score: '0.087',
                income_deprivation_affecting_older_people_rank: '24872',
                income_deprivation_affecting_older_people_decile: '8',
                children_and_young_people_subdomain_score: '0.348',
                children_and_young_people_subdomain_rank: '10879',
                children_and_young_people_subdomain_decile: '4',
                adult_skills_subdomain_score: '0.359',
                adult_skills_subdomain_rank: '9977',
                adult_skills_subdomain_decile: '4',
                geographical_barriers_subdomain_score: '0.233',
                geographical_barriers_subdomain_rank: '11852',
                geographical_barriers_subdomain_decile: '4',
                wider_barriers_subdomain_score: '-0.596',
                wider_barriers_subdomain_rank: '18742',
                wider_barriers_subdomain_decile: '6',
                indoors_subdomain_score: '-0.576',
                indoors_subdomain_rank: '24455',
                indoors_subdomain_decile: '8',
                outdoors_subdomain_score: '0.109',
                outdoors_subdomain_rank: '14350',
                outdoors_subdomain_decile: '5',
                total_population_mid_2012: '1453',
                dependent_children_aged_015_mid_2012: '233',
                population_aged_1659_mid_2012: '739',
                older_population_aged_60_and_over_mid_2012: '481',
                working_age_population_185964: '748.25'
              },
              {
                lsoa_code_2011: 'E01031370',
                lsoa_name_2011: 'Adur 001E',
                local_authority_district_code_2013: 'E07000223',
                index_of_multiple_deprivation_score: 'Adur',
                index_of_multiple_deprivation_rank: '15643',
                index_of_multiple_deprivation_decile: '5',
                income_score: '0.102',
                income_rank: '17918',
                income_decile: '6.000',
                employment_score: '0.115',
                employment_rank: '13322',
                employment_decile: '5',
                education_skills_and_training_score: '32.056',
                education_skills_and_training_rank: '7819',
                education_skills_and_training_decile: '3',
                health_deprivation_and_disability_score: '0.082',
                health_deprivation_and_disability_rank: '14893',
                health_deprivation_and_disability_decile: '5',
                crime_score: '0.182',
                crime_rank: '13723',
                crime_decile: '5',
                barriers_to_housing_and_services_score: '15.482',
                barriers_to_housing_and_services_rank: '22433',
                barriers_to_housing_and_services_decile: '7',
                living_environment_score: '15.378',
                living_environment_rank: '18191',
                living_environment_decile: '6',
                income_deprivation_affecting_children_index_score: '0.117',
                income_deprivation_affecting_children_index_rank: '19304',
                income_deprivation_affecting_children_index_decile: '6',
                income_deprivation_affecting_older_people_score: '0.131',
                income_deprivation_affecting_older_people_rank: '18443',
                income_deprivation_affecting_older_people_decile: '6',
                children_and_young_people_subdomain_score: '0.840',
                children_and_young_people_subdomain_rank: '5112',
                children_and_young_people_subdomain_decile: '2',
                adult_skills_subdomain_score: '0.338',
                adult_skills_subdomain_rank: '11874',
                adult_skills_subdomain_decile: '4',
                geographical_barriers_subdomain_score: '-0.083',
                geographical_barriers_subdomain_rank: '17223',
                geographical_barriers_subdomain_decile: '6',
                wider_barriers_subdomain_score: '-0.086',
                wider_barriers_subdomain_rank: '15891',
                wider_barriers_subdomain_decile: '5',
                indoors_subdomain_score: '-0.256',
                indoors_subdomain_rank: '20214',
                indoors_subdomain_decile: '7',
                outdoors_subdomain_score: '0.321',
                outdoors_subdomain_rank: '11202',
                outdoors_subdomain_decile: '4',
                total_population_mid_2012: '1443',
                dependent_children_aged_015_mid_2012: '306',
                population_aged_1659_mid_2012: '799',
                older_population_aged_60_and_over_mid_2012: '338',
                working_age_population_185964: '795.50'
              },
              {
                lsoa_code_2011: 'E01031374',
                lsoa_name_2011: 'Adur 001F',
                local_authority_district_code_2013: 'E07000223',
                index_of_multiple_deprivation_score: 'Adur',
                index_of_multiple_deprivation_rank: '21176',
                index_of_multiple_deprivation_decile: '7',
                income_score: '0.072',
                income_rank: '23201',
                income_decile: '8.000',
                employment_score: '0.084',
                employment_rank: '18948',
                employment_decile: '6',
                education_skills_and_training_score: '14.261',
                education_skills_and_training_rank: '18006',
                education_skills_and_training_decile: '6',
                health_deprivation_and_disability_score: '-0.183',
                health_deprivation_and_disability_rank: '18846',
                health_deprivation_and_disability_decile: '6',
                crime_score: '0.128',
                crime_rank: '14566',
                crime_decile: '5',
                barriers_to_housing_and_services_score: '15.696',
                barriers_to_housing_and_services_rank: '22170',
                barriers_to_housing_and_services_decile: '7',
                living_environment_score: '22.053',
                living_environment_rank: '13264',
                living_environment_decile: '5',
                income_deprivation_affecting_children_index_score: '0.060',
                income_deprivation_affecting_children_index_rank: '26912',
                income_deprivation_affecting_children_index_decile: '9',
                income_deprivation_affecting_older_people_score: '0.091',
                income_deprivation_affecting_older_people_rank: '24048',
                income_deprivation_affecting_older_people_decile: '8',
                children_and_young_people_subdomain_score: '-0.257',
                children_and_young_people_subdomain_rank: '20337',
                children_and_young_people_subdomain_decile: '7',
                adult_skills_subdomain_score: '0.309',
                adult_skills_subdomain_rank: '14998',
                adult_skills_subdomain_decile: '5',
                geographical_barriers_subdomain_score: '-0.052',
                geographical_barriers_subdomain_rank: '16671',
                geographical_barriers_subdomain_decile: '6',
                wider_barriers_subdomain_score: '-0.118',
                wider_barriers_subdomain_rank: '16108',
                wider_barriers_subdomain_decile: '5',
                indoors_subdomain_score: '0.307',
                indoors_subdomain_rank: '11993',
                indoors_subdomain_decile: '4',
                outdoors_subdomain_score: '0.194',
                outdoors_subdomain_rank: '13019',
                outdoors_subdomain_decile: '4',
                total_population_mid_2012: '1499',
                dependent_children_aged_015_mid_2012: '258',
                population_aged_1659_mid_2012: '830',
                older_population_aged_60_and_over_mid_2012: '411',
                working_age_population_185964: '840.00'
              }
            ]
          )
          done()
        }
      }
    )
  })
})
